version: '3.8'

services:
  db:
    build: ./db
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_DB: url_alias_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./dump:/var/lib/postgresql/data

  api:
    build: ./url-alias-service
    container_name: api
    #    #    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - db